CREATE TABLE IF NOT EXISTS player(
	timestamp INTEGER  NOT NULL,
	accountId INTEGER  NOT NULL,
	summonerName VARCHAR(30)  NOT NULL,
	iconId INTEGER  NOT NULL,
	PRIMARY KEY (accountId)
);

CREATE TABLE IF NOT EXISTS match(
	timestamp INTEGER  NOT NULL,
	matchId INTEGER  NOT NULL,
	redSideWon INTEGER CHECK(redSideWon IN (0, 1)) NOT NULL,
	length INTEGER  NOT NULL,
	date INTEGER  NOT NULL,
	PRIMARY KEY (matchId)
);

CREATE TABLE IF NOT EXISTS team(
	timestamp INTEGER  NOT NULL,
	matchId INTEGER  NOT NULL,
	isRedSide INTEGER CHECK(isRedSide IN (0, 1)) NOT NULL,
	dragons INTEGER  NOT NULL,
	barons INTEGER  NOT NULL,
	towers INTEGER  NOT NULL,
	inhibs INTEGER  NOT NULL,
	ban0 VARCHAR(20)  NOT NULL,
	ban1 VARCHAR(20)  NOT NULL,
	ban2 VARCHAR(20)  NOT NULL,
	ban3 VARCHAR(20)  NOT NULL,
	ban4 VARCHAR(20)  NOT NULL,
	PRIMARY KEY (matchId, isRedSide),
	FOREIGN KEY (matchId) REFERENCES match(matchId)
);

CREATE TABLE IF NOT EXISTS teamPlayer(
	timestamp INTEGER  NOT NULL,
	matchId INTEGER  NOT NULL,
	accountId INTEGER  NOT NULL,
	champion VARCHAR(20)  NOT NULL,
	isRedSide INTEGER CHECK(isRedSide IN (0, 1)) NOT NULL,
	kills INTEGER  NOT NULL,
	deaths INTEGER  NOT NULL,
	assists INTEGER  NOT NULL,
	cs INTEGER  NOT NULL,
	doubles INTEGER  NOT NULL,
	triples INTEGER  NOT NULL,
	quadras INTEGER  NOT NULL,
	pentas INTEGER  NOT NULL,
	kp INTEGER  NOT NULL,
	dmgDealt INTEGER  NOT NULL,
	dmgTaken INTEGER  NOT NULL,
	gold INTEGER  NOT NULL,
	spell1 VARCHAR(30)  NOT NULL,
	spell2 VARCHAR(30)  NOT NULL,
	item0 INTEGER  NOT NULL,
	item1 INTEGER  NOT NULL,
	item2 INTEGER  NOT NULL,
	item3 INTEGER  NOT NULL,
	item4 INTEGER  NOT NULL,
	item5 INTEGER  NOT NULL,
	item6 INTEGER  NOT NULL,
	keyStoneUrl VARCHAR(100)  NOT NULL,
	healing INTEGER  NOT NULL,
	vision INTEGER  NOT NULL,
	ccTime INTEGER  NOT NULL,
	firstBlood INTEGER CHECK(firstBlood IN (0, 1)) NOT NULL,
	turrets INTEGER  NOT NULL,
	inhibs INTEGER  NOT NULL,
	PRIMARY KEY (matchId, accountId),
	FOREIGN KEY (matchId) REFERENCES match(matchId),
	FOREIGN KEY (accountId) REFERENCES player(accountId)
);